Updating TSO500 DNA for new somatic nextflow pipeline
AWGL/auto_qc pull request #114
Opened 2022-12-07 10:28 UTC by SophieS9

Changes made to:

- Config file - different end point files for TSO500 DNA pipeline
- TSO500 parser - handling new files
- View Run Analysis html - now displays breakdown of FastQC checks as a "hovering box" about the FastQC result. This includes a new function in the models.  
- Unit tests and test data for TSO500 DNA.

Tested with outputs from /data/output/validations//somatic_enrichment_nextflow/220608_A01771_0044_AH7VK5DRX2_run4_new_fastqc/

Unit tests complete with no errors.

2023-07-26 11:26 UTC, SophieS9 commented
- Merged development branch, resolved conflicts and checked that everything is still working. All good :)
- ctDNA doesn't display the FastQC metrics when you hover over it, but all of the other runs do. 

Test data (one TSO500 and one ctDNA) on hard drive with sticker under AutoQC_SVD_Test/

2023-08-03 09:22 UTC, Istaisa commented
Unit tests all pass.

TSO500 DNA runs from new pipeline upload as expected and display correct metrics.

Need to test:
- Full RNA/ctDNA run
- TSO500 DNA runs from old pipeline already in database still display correctly

2023-08-04 09:23 UTC, Istaisa commented
update_database.py will need changing to account for the new TSO500 folder structure

line 504 should be something like `run_data_dir = Path(results_dir).joinpath(f"{run_analysis.run.run_id}/TSO500/")`

2023-08-04 09:27 UTC, Istaisa requested changes
- Unit tests all pass
- Manual testing of DNA, RNA and ctDNA runs all fine
- Hovering FastQC stats is great!
- Code logic makes sense

Summary of changes requested:
- Updates to local config
- Alteration to update_database.py for new folder structure
- Point about code comment is up to you

Unable to test that old TSO500 runs still display correctly due to quirk of changing git branch breaking local AutoQC but Sophie has tested - we'll check this when it goes live. I can't see anything in the code that makes me think this should be a problem though.

2023-08-04 09:27 UTC, Istaisa commented on config/config_local.yaml
Config changes needed for local config:

- Remove ] on line 51 
- Change the ctDNA local config to reflect the gen01 config

2023-08-04 09:27 UTC, Istaisa commented on pipelines/TSO500_pipeline.py
> +
not necessary but might be useful if someone else picks this up in the future

2023-08-08 10:19 UTC, SophieS9 commented
Code review changes all done as above. Changed the structure of the test data to reflect the changes.

2023-09-19 12:47 UTC, SophieS9 commented
Addition of minor bug fixes as code reviewed in https://github.com/AWGL/auto_qc/pull/157.

2023-09-19 12:47 UTC, merged